🐼 Pandas Tutorial › Cleaning Data &nbsp;·&nbsp; *Bài 12/15*

[« Pandas - Cleaning Data of Wrong Format](011_pandas_cleaning_wrong_format.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Pandas - Removing Duplicates »](013_pandas_removing_duplicates.ipynb)

# Pandas - Fixing Wrong Data

> 📖 **Học song song trên W3Schools:** [pandas_cleaning_wrong_data.asp](https://www.w3schools.com/python/pandas/pandas_cleaning_wrong_data.asp)
>
> 🎯 **Trong bài này:** Wrong Data · Replacing Values · Removing Rows · ➕ Mở rộng: Cách "vector hoá" không cần vòng lặp

## Wrong Data — Dữ liệu sai

"Dữ liệu sai" không nhất thiết là ô trống hay sai định dạng — nó có thể chỉ là **giá trị không hợp lý**, như ai đó gõ "199" thay vì "1.99".

Đôi khi bạn phát hiện bằng cách nhìn tập dữ liệu, vì bạn có kỳ vọng về giá trị hợp lý.

Trong tập dữ liệu, hàng 7 có thời lượng **450**, trong khi các hàng khác chỉ 45-60:

In [1]:
import pandas as pd

df = pd.read_csv('dirtydata.csv')
print(df.loc[5:9])

   Duration        Date  Pulse  Maxpulse  Calories
5        60  2020/12/06    103       121     298.8
6        60  2020/12/07    130       148     330.1
7       450  2020/12/08    104       122     400.6
8        60  2020/12/09    110       130     343.1
9        60  2020/12/10    110       137     341.8


Không phải lúc nào cũng là lỗi — nhưng với **thời lượng tập luyện** (tính bằng phút), 450 phút (7,5 giờ) gần như chắc chắn là gõ nhầm từ 45.

## Replacing Values — Thay giá trị

Cách sửa là thay bằng giá trị khác.

Trường hợp này có thể đoán là gõ nhầm, nên ta thay "450" bằng "45":

In [2]:
import pandas as pd

df = pd.read_csv('dirtydata.csv')

df.loc[7, 'Duration'] = 45

print(df.loc[7])

Duration            45
Date        2020/12/08
Pulse              104
Maxpulse           122
Calories         400.6
Name: 7, dtype: object


Với tập dữ liệu nhỏ, có thể sửa từng giá trị. Với dữ liệu lớn, nên đặt **quy tắc** — ví dụ: giá trị Duration không được vượt quá 120 — rồi duyệt để sửa:

In [3]:
import pandas as pd

df = pd.read_csv('dirtydata.csv')

for x in df.index:
    if df.loc[x, "Duration"] > 120:
        df.loc[x, "Duration"] = 120

print(df["Duration"].max())

120


## Removing Rows — Xoá hàng

Cách khác là **xoá** các hàng có dữ liệu sai. Như vậy không cần tìm giá trị thay thế, và khả năng cao hàng đó không cần thiết cho việc phân tích:

In [4]:
import pandas as pd

df = pd.read_csv('dirtydata.csv')

for x in df.index:
    if df.loc[x, "Duration"] > 120:
        df.drop(x, inplace=True)

print(df.shape)

(31, 5)


## ➕ Mở rộng: Cách "vector hoá" không cần vòng lặp

In [5]:
import pandas as pd

df = pd.read_csv('dirtydata.csv')
df["Duration"] = df["Duration"].clip(upper=120)     # thay giá trị > 120 bằng 120
clean = df[df["Duration"] <= 120]                   # hoặc lọc bỏ
print(df["Duration"].max(), clean.shape)

120 (32, 5)


---

## 🧠 Ghi nhớ nhanh

> - Dữ liệu sai = giá trị **không hợp lý** (gõ nhầm, vượt ngưỡng).
> - Sửa một ô: `df.loc[hàng, 'cột'] = giá_trị`.
> - Đặt quy tắc + duyệt `df.index` để **thay** hoặc **xoá** (`df.drop(x)`).
> - Gọn hơn: `clip()` hoặc lọc boolean `df[df["c"] <= 120]`.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Câu lệnh nào gán giá trị 45 vào cột `Duration` của hàng 7?

- **A.** `df.loc[7, 'Duration'] = 45`
- **B.** `df.set(7, 'Duration', 45)`
- **C.** `df.Duration(7) = 45`
- **D.** `df[7]['Duration'] = 45`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: A** — `df.loc[7, 'Duration'] = 45`

</details>

---

[« Pandas - Cleaning Data of Wrong Format](011_pandas_cleaning_wrong_format.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Pandas - Removing Duplicates »](013_pandas_removing_duplicates.ipynb)